---
branches:
  only:
  - source
language: ruby
rvm:
  - 2.0.0
  - 1.9.3
before_script:
- export REPO_URL="https://$GH_TOKEN@github.com/$GH_REPO.git"
- bundle exec rake setup_github_pages[$REPO_URL]
---script: bundle exec rake install; bundle exec rake generate
script:
- bundle exec rake generate
after_script:
- bundle exec rake deploy
env:
  global:
  - GH_REPO="gutti/gutti.github.io"
  - secure: "T+OqFp6R7bL4q77/MUvlS/TP9IHSi6or41QiJoHdKKDjWTOjzK5oOjsvoC8kEH4lH9fddjHiipWVNyVTT+SUJO8H5ZzV24WYAXbUaa8BgvepQxu31vI2p5wtnLHOSbPWlPuuepZuCgxqz+cLRUO0rxRCm2UTZTJiFB2xdO7RjVE="
